# -*- coding: utf-8 -*-
"""PILOT NAVIGATION SYSTEM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MXjSUmSQZgLN8qYrgVNhkUChK5hQEHck
"""

#pilot navigation system
alt=int(input("please enter the Altitude = "))
if alt == 3000:
  print("YOU ARE SAFE FOR LANDING")
elif 6000>alt>3000:
  print("COME DOWN TO 3000ft AND OPEN LANDING GEAR")
elif alt>6000:
  print("YOU ARE NOT ALLOWED TO LAND AND GO AROUND")  
else:
  print("YOU ARE NOT SAFE FOR LANDING")